### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by mrcodegit** [Sergej-Vlasov/vite-react-ts#5]
Thank you for taking the time to complete our test :) 

I added 2 issues to the repository. If you have some spare time please take a look.

It is a fundamental part of the interview process. There are no time constraints from my side, so that you can provide fixes and discussion on your own time, at your own pace.

**Comment by Sergej-Vlasov** [comment]
Thank you for the time taken to review the code! 

I have now resolved and closed the issues you created. 
Feel free to follow up on previous issues or open new ones.
