### ISSUE TITLE
1. Search input loses focus

### ISSUE THREAD

**Issue by mrcodegit** [Sergej-Vlasov/vite-react-ts#6]
Reproduction:

1. type something in search
2. wait
3. input loses focus

Expectation:
- Input keeps focus

**Comment by Sergej-Vlasov** [comment]
Hi, thank you for pointing out the bug. It is quite an interesting one.

The main bug reason is that internal `<TextField />` logic resets the `focus` styles after `disabled` is applied and removed.
Main evidence for that is that this bug does not exist on the classic html `<input />`. If you replace the TextField with 
```
<input value={searchQuery} disabled={loading} onChange={handleInputChange} />
```
...then the bug disappears.

Solutions that failed:

- adding `inputRef` and controlling the focus state with `inputRef.current.focus()` in the debounce or useEffect. For some reason this was not possible although the same logic would work if you put in the button, perhaps some standards that prevent programatic focus

Solutions that worked:
- preventing the `onChange` function if `loading` is `true`. This is by far not ideal and needs to be supplemented with additional styles to put input visually into disabled state.

**Comment by mrcodegit** [comment]
Thank you for solving this, I confirm the bug is gone. I appreciate detailed description of different approaches you have tried
