### ISSUE TITLE
2. Split App.tsx

### ISSUE THREAD

**Issue by mrcodegit** [Sergej-Vlasov/vite-react-ts#7]
Could please we extract some components from App.tsx ?

**Comment by Sergej-Vlasov** [comment]
The following actions were taken to split the `App.tsx` file:

- moved `LoadingPlaceholder` into separate component with dynamic text prop
- moved `EmptyPlaceholder` into separate component with dynamic text prop
- extracted Table component into `GithubReposTable` file and incorporated above components

Considerations:
- could make `GithubReposTable` into a fully static table with dynamic headers and rows. For reference it could have the following structure of props:
``` 
interface IStaticTableProps {
  headers?: React.ReactNode[];
  rows: React.ReactNode[] | undefined;
{
```
- Did not export input component as it would actually make more code than save.

Let me know if this does not satisfy your requirement of the `App.tsx` split that you invisioned. Can do further splitting of building blocks of table.

**Comment by mrcodegit** [comment]
Thank you for splitting, no further actions required :)
